//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatesMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatesMap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadioApp.Resources.StatesMap", typeof(StatesMap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chernihiv.
        /// </summary>
        internal static string Chernihiv {
            get {
                return ResourceManager.GetString("Chernihiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chernivtsi.
        /// </summary>
        internal static string Chernivtsi {
            get {
                return ResourceManager.GetString("Chernivtsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnipropetrovs&apos;k.
        /// </summary>
        internal static string Dnepr {
            get {
                return ResourceManager.GetString("Dnepr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivano-Frankivs&apos;k.
        /// </summary>
        internal static string Ivano_Frankivsk {
            get {
                return ResourceManager.GetString("Ivano Frankivsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kharkiv.
        /// </summary>
        internal static string Kharkiv {
            get {
                return ResourceManager.GetString("Kharkiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kherson.
        /// </summary>
        internal static string Kherson {
            get {
                return ResourceManager.GetString("Kherson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmel&apos;nyts&apos;kyy.
        /// </summary>
        internal static string Khmelnytskyi {
            get {
                return ResourceManager.GetString("Khmelnytskyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiev.
        /// </summary>
        internal static string Kiev {
            get {
                return ResourceManager.GetString("Kiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirovohrad.
        /// </summary>
        internal static string Kropyvnytskyi {
            get {
                return ResourceManager.GetString("Kropyvnytskyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiev.
        /// </summary>
        internal static string Kyiv {
            get {
                return ResourceManager.GetString("Kyiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;viv.
        /// </summary>
        internal static string Lviv {
            get {
                return ResourceManager.GetString("Lviv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;viv.
        /// </summary>
        internal static string Lviv_Oblast {
            get {
                return ResourceManager.GetString("Lviv Oblast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivne.
        /// </summary>
        internal static string Rivne {
            get {
                return ResourceManager.GetString("Rivne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinnytsya.
        /// </summary>
        internal static string Vinnytsia {
            get {
                return ResourceManager.GetString("Vinnytsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaporizhzhya.
        /// </summary>
        internal static string Zaporizhzhia {
            get {
                return ResourceManager.GetString("Zaporizhzhia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhytomyr.
        /// </summary>
        internal static string Zhytomyr {
            get {
                return ResourceManager.GetString("Zhytomyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donets&apos;k.
        /// </summary>
        internal static string Донецк {
            get {
                return ResourceManager.GetString("Донецк", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiev.
        /// </summary>
        internal static string Київська {
            get {
                return ResourceManager.GetString("Київська", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luhans&apos;k.
        /// </summary>
        internal static string Луганск {
            get {
                return ResourceManager.GetString("Луганск", resourceCulture);
            }
        }
    }
}
